#pragma once

#ifndef USE_SCOPE_ANGLE
#define USE_SCOPE_ANGLE 1
#endif

#ifndef USE_RANDOM_SEED
#define USE_RANDOM_SEED 1
#endif 

#ifndef USE_EXPORT_HEIGHT_MAP
#define USE_EXPORT_HEIGHT_MAP 0
#endif 

#ifndef USE_MAX_SLOPE_ANGLE
#define USE_MAX_SLOPE_ANGLE 0
#endif 

#ifndef USE_POS_RELATIVE
#define USE_POS_RELATIVE 0
#endif

#ifndef USE_SIMPLE_PC_OUTPUT
#define USE_SIMPLE_PC_OUTPUT 0
#endif

#pragma once

#ifndef USE_OUTPUT_HEIGHT_MAP_CSV
#define USE_OUTPUT_HEIGHT_MAP_CSV 0
#endif

#ifndef USE_OUTPUT_ONLY_POSITIVE_HEIGHT
#define USE_OUTPUT_ONLY_POSITIVE_HEIGHT 0
#endif

#ifndef USE_CELLINFO_HEIGHT_FOR_POINT_INSTANCE
#define USE_CELLINFO_HEIGHT_FOR_POINT_INSTANCE 1
#endif

#ifndef USE_DISPLAY_HEIGHTMAP_MASK_RESULT
#define USE_DISPLAY_HEIGHTMAP_MASK_RESULT 1
#endif

#ifndef USE_OUTPUT_INSTANCE_IDSTRING
#define USE_OUTPUT_INSTANCE_IDSTRING 0
#endif

#ifndef PI
#define PI       3.14159265358979323846   // pi
#endif // !PI

#ifndef UNAVAILBLE_NEG_HEIGHT
#define UNAVAILBLE_NEG_HEIGHT	-20000
#endif // !UNAVAILBLE_NEG_HEIGHT

#ifndef UNAVAILBLE_POS_HEIGHT
#define UNAVAILBLE_POS_HEIGHT	20000
#endif // !UNAVAILBLE_POS_HEIGHT

#ifndef CAVE_DISTANCE_LIMIT_TREE
#define CAVE_DISTANCE_LIMIT_TREE	    150
#endif // !CAVE_DISTANCE_LIMIT_TREE

#ifndef CAVE_DISTANCE_LIMIT_POI
#define CAVE_DISTANCE_LIMIT_POI	    100
#endif // !CAVE_DISTANCE_LIMIT_POI