import struct
import numpy as np
from PIL import Image
import os

def load_distance_field(file_path, meter_is_double=True):
    """
    Load binary file generated by RoadDistanceField::SaveToFile.
    
    File Structure based on C++ code:
    1. width_       (int, 4 bytes)
    2. height_      (int, 4 bytes)
    3. meterPerPixel_ (double or float, 8 or 4 bytes) 
       -> C++ uses sizeof(meterPerPixel_), usually double if distanceMap is double.
    4. distanceMap_ (double array, width * height * 8 bytes)
       -> C++ explicitly uses sizeof(double) for data.
    
    Data Order: Column-major (index = col * height + row)
    
    Args:
        file_path: Path to the binary file.
        meter_is_double: If True, reads meterPerPixel as double (8 bytes). 
                         If False, reads as float (4 bytes). 
                         Default True to match high-precision double data.
    """
    if not os.path.exists(file_path):
        print(f"Error: File not found - {file_path}")
        return None, None, None, None

    try:
        with open(file_path, 'rb') as f:
            # 1. Read width (int)
            width_data = f.read(4)
            if len(width_data) < 4: raise ValueError("File corrupted: Cannot read width")
            width = struct.unpack('i', width_data)[0]

            # 2. Read height (int)
            height_data = f.read(4)
            if len(height_data) < 4: raise ValueError("File corrupted: Cannot read height")
            height = struct.unpack('i', height_data)[0]

            # 3. Read meterPerPixel
            # Based on C++: file.write(..., sizeof(meterPerPixel_))
            # Assuming double (8 bytes) to match the double data array, but configurable.
            if meter_is_double:
                meter_data = f.read(8)
                if len(meter_data) < 8: raise ValueError("File corrupted: Cannot read meterPerPixel (expected double)")
                meter_per_pixel = struct.unpack('d', meter_data)[0]
                meter_type_str = "double (8 bytes)"
            else:
                meter_data = f.read(4)
                if len(meter_data) < 4: raise ValueError("File corrupted: Cannot read meterPerPixel (expected float)")
                meter_per_pixel = struct.unpack('f', meter_data)[0]
                meter_type_str = "float (4 bytes)"

            print(f"Header Info: Width={width}, Height={height}")
            print(f"MeterPerPixel: {meter_per_pixel:.15f} ({meter_type_str})")

            if width <= 0 or height <= 0:
                print("Error: Invalid dimensions in file header")
                return None, None, None, None

            # 4. Read distance map data
            # C++ Code: file.write(..., distanceMap_.size() * sizeof(double))
            # We MUST read as double ('d'), 8 bytes per value.
            expected_count = width * height
            expected_bytes = expected_count * 8  # 8 bytes for double
            
            data_bytes = f.read(expected_bytes)
            
            if len(data_bytes) != expected_bytes:
                print(f"Warning: Data size mismatch. Expected {expected_bytes} bytes, got {len(data_bytes)} bytes.")
                if len(data_bytes) == 0:
                    return None, None, None, None
                # Adjust count if partial read
                actual_count = len(data_bytes) // 8
                print(f"Attempting to process partial data: {actual_count} values...")
            else:
                actual_count = expected_count

            # Unpack as doubles ('d')
            raw_data = struct.unpack(f'{actual_count}d', data_bytes)
            
            # Convert to numpy array
            np_array = np.array(raw_data, dtype=np.float64)
            
            # Reshape according to C++ Column-Major logic: index = col * height + row
            # Shape becomes (width, height)
            np_array_col_major = np_array.reshape((width, height))
            
            # Transpose to get standard Image format (height, width) i.e., (row, col)
            distance_map = np_array_col_major.T
            
            return distance_map, width, height, meter_per_pixel

    except Exception as e:
        print(f"Error reading file: {e}")
        import traceback
        traceback.print_exc()
        return None, None, None, None

def normalize_and_colorize(distance_map, reverse=False):
    """
    Convert distance map to RGB image.
    
    Mapping Rules:
    Normal (reverse=False):
      - 0.0 -> Black (0, 0, 0)
      - 1.0 -> Red (255, 0, 0)
      
    Reverse (reverse=True):
      - 0.0 -> Red (255, 0, 0)
      - 1.0 -> Black (0, 0, 0)
      
    Values > 1.0 are clipped to the max color intensity.
    Invalid values (inf/nan) are set to Black.
    """
    if distance_map is None:
        return None

    h, w = distance_map.shape
    
    # Create output RGB array (H, W, 3), initialized to Black
    rgb_image = np.zeros((h, w, 3), dtype=np.uint8)
    
    # Mask for valid finite numbers
    valid_mask = np.isfinite(distance_map)
    valid_data = distance_map[valid_mask]
    
    if valid_data.size == 0:
        print("Warning: No valid finite data found in the map.")
        return Image.fromarray(rgb_image)

    target_max = 1.0
    
    # Normalize: divide by 1.0
    normalized = valid_data / target_max
    
    # Clip to [0.0, 1.0]
    normalized = np.clip(normalized, 0.0, 1.0)

    # Apply Reverse Logic
    if reverse:
        # 0.0 becomes 1.0 (Red), 1.0 becomes 0.0 (Black)
        normalized = 1.0 - normalized

    # Map to Red Channel (0-255)
    red_channel = (normalized * 255.0).astype(np.uint8)
    
    # Assign to RGB image
    rgb_image[valid_mask, 0] = red_channel  # R
    rgb_image[valid_mask, 1] = 0            # G
    rgb_image[valid_mask, 2] = 0            # B
    
    return Image.fromarray(rgb_image)

def main():
    # ==========================================
    # Configuration Area
    # ==========================================
    
    # Input binary file path (generated by C++ SaveToFile)
    INPUT_FILE = "road_distance.bin"  
    
    # Output image path (.png or .jpg)
    OUTPUT_FILE = "output_result.png"
    
    # Color Mapping Mode
    # False: 0.0=Black, 1.0=Red (Standard Distance Field)
    # True:  0.0=Red, 1.0=Black (Inverse)
    REVERSE = False
    
    # MeterPerPixel Precision Setting
    # The C++ code writes sizeof(meterPerPixel_). 
    # Since distanceMap is explicitly double, meterPerPixel is likely double too.
    # Set to True if your C++ member variable 'meterPerPixel_' is a 'double'.
    # Set to False only if it is explicitly a 'float'.
    METER_IS_DOUBLE = True 
    
    # ==========================================
    # Execution
    # ==========================================

    print(f"--- Starting Processing ---")
    print(f"Input: {INPUT_FILE}")
    
    data, w, h, meter_per_pixel = load_distance_field(INPUT_FILE, meter_is_double=METER_IS_DOUBLE)

    if data is None:
        print("Failed to load data. Exiting.")
        return

    print(f"Data loaded: {w}x{h} grid")
    print(f"Data Type: float64 (double)")
    print(f"Value Range: Min={data.min():.6f}, Max={data.max():.6f}")
    
    # Check for clipping
    count_over_1 = np.sum(data > 1.0)
    if count_over_1 > 0:
        print(f"Note: {count_over_1} pixels > 1.0m will be clipped to max color intensity.")

    # Mode info
    mode_str = "REVERSE (0.0=Red, 1.0=Black)" if REVERSE else "NORMAL (0.0=Black, 1.0=Red)"
    print(f"Color Mode: {mode_str}")
    
    print("Generating image...")
    img = normalize_and_colorize(data, reverse=REVERSE)

    if img:
        img.save(OUTPUT_FILE)
        print(f"Success! Image saved to: {OUTPUT_FILE}")
    else:
        print("Image generation failed.")

if __name__ == "__main__":
    main()

def main():
        # ==========================================
    # Configuration Area
    # ==========================================

    # Input binary file path (generated by C++ SaveToFile)
    INPUT_FILE = "D:\\Downloads\\XCTreeCreation\\Tree_Big_Creation\\sommothlayer_output\\12_4_2\\12_4_2_world_road_distance.dat"
    
    # Output image path (.png or .jpg)
    OUTPUT_FILE = "D:\\Downloads\\XCTreeCreation\\Tree_Big_Creation\\sommothlayer_output\\12_4_2\\12_4_2_world_road_distance.png"
    
    # Color Mapping Mode
    # False: 0.0=Black, 1.0=Red (Standard Distance Field)
    # True:  0.0=Red, 1.0=Black (Inverse)
    REVERSE = True
    
    # MeterPerPixel Precision Setting
    # The C++ code writes sizeof(meterPerPixel_). 
    # Since distanceMap is explicitly double, meterPerPixel is likely double too.
    # Set to True if your C++ member variable 'meterPerPixel_' is a 'double'.
    # Set to False only if it is explicitly a 'float'.
    METER_IS_DOUBLE = True 
    
    # ==========================================
    # Execution
    # ==========================================

    print(f"--- Starting Processing ---")
    print(f"Input: {INPUT_FILE}")
    
    print(f"Loading file: {INPUT_FILE} ...")
    data, w, h, meter_per_pixel = load_distance_field(INPUT_FILE, meter_is_double=METER_IS_DOUBLE)

    if data is None:
        print("Load failed, exiting.")
        return

    print(f"Data loaded: {w}x{h} grid")
    print(f"Data Type: float64 (double)")
    print(f"Value Range: Min={data.min():.6f}, Max={data.max():.6f}")
    
    # Check for clipping
    over_1_count = np.sum(data > 1.0)
    if over_1_count > 0:
        print(f"Note: {over_1_count} pixels have values greater than 1.0, will be clipped.")
        
     # Mode info
    mode_str = "REVERSE (0.0=Red, 1.0=Black)" if REVERSE else "NORMAL (0.0=Black, 1.0=Red)"
    print(f"Color Mode: {mode_str}")

    # Print color mapping mode
    if REVERSE:
        print("Color mode: REVERSE (0.0=Red, 1.0=Black)")
    else:
        print("Color mode: NORMAL (0.0=Black, 1.0=Red)")

    print("Generating image...")
    img = normalize_and_colorize(data, reverse=REVERSE)

    if img:
        img.save(OUTPUT_FILE)
        print(f"Success! Image saved to: {OUTPUT_FILE}")
    else:
        print("Image generation failed.")

if __name__ == "__main__":
    main()
    
  
    
    